version: "2.1"

services:
  live-streaming-origin-1:
    image: docker.io/unifiedstreaming/live-streaming-origin:stable
    networks:
      docker-network:
        aliases:
          - "origin-1"
    environment:
      - LOG_LEVEL=warn
      - UspLicenseKey
      - PUB_POINT_NAME=channel
      - PUB_POINT_OPTS=--archiving=1 --archive_length=180 --archive_segment_length=5 --dvr_window_length=60 --restart_on_encoder_reconnect --hls.minimum_fragment_length=48/25 --hls.client_manifest_version=4 --hls.no_audio_only --mpd.minimum_fragment_length=48/25 --mpd.segment_template=time
    healthcheck:
      test: kill -0 1
      interval: 2s
      timeout: 5s
      retries: 30

  live-streaming-ffmpeg-1:
    image: docker.io/unifiedstreaming/live-streaming-ffmpeg:stable
    environment:
      - PUB_POINT_URI=http://origin-1/channel/channel.isml
      - 'TRACKS={ "video": [ { "width": 1280, "height": 720, "bitrate": "300k", "codec": "libx264", "framerate": 25, "gop": 48, "timescale": 25 } ], "audio": [ { "samplerate": 48000, "bitrate": "64k", "codec": "aac", "language": "eng", "timescale": 48000, "frag_duration_micros": 1920000 } ] }'
    depends_on:
      live-streaming-origin-1:
        condition: service_healthy
    restart: always

    networks:
      docker-network:


  live-streaming-origin-2:
    image: docker.io/unifiedstreaming/live-streaming-origin:stable
    environment:
      - LOG_LEVEL=warn
      - UspLicenseKey
      - PUB_POINT_NAME=channel
      - PUB_POINT_OPTS=--archiving=1 --archive_length=180 --archive_segment_length=5 --dvr_window_length=60 --restart_on_encoder_reconnect --hls.minimum_fragment_length=48/25 --hls.client_manifest_version=4 --hls.no_audio_only --mpd.minimum_fragment_length=48/25 --mpd.segment_template=time
    healthcheck:
      test: kill -0 1
      interval: 2s
      timeout: 5s
      retries: 30
    networks:
      docker-network:
        aliases:
          - "origin-2"

  live-streaming-ffmpeg-2:
    image: docker.io/unifiedstreaming/live-streaming-ffmpeg:stable
    environment:
      - PUB_POINT_URI=http://origin-2/channel/channel.isml
      - 'TRACKS={ "video": [ { "width": 1280, "height": 720, "bitrate": "300k", "codec": "libx264", "framerate": 25, "gop": 48, "timescale": 25 } ], "audio": [ { "samplerate": 48000, "bitrate": "64k", "codec": "aac", "language": "eng", "timescale": 48000, "frag_duration_micros": 1920000 } ] }'
    depends_on:
      live-streaming-origin-2:
        condition: service_healthy
    restart: always

    networks:
      docker-network:

  nginx:
    image: nginx:1
    platform: linux/amd64
    domainname: origin.test
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./origin.conf:/etc/nginx/conf.d/origin.conf
    networks:
      docker-network:
        aliases:
          - origin.test
networks:
  docker-network:
